### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [noderosa/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by noderosa** [comment]
Thank you, Billy for the feedback.

I added this
meta name="viewport" content="width=device-width, initial-scale=1"

to the inside of head of application.html.erb.

I just checked the app on my phone (which I should have done in the first place..) and I think it's responsive now.

https://splurty-chie-miyajima.herokuapp.com/

So my question is that even if I use "col-xs-4" etc, if there's no mobile meta tag, it won't be responsive?

Thank you very much,
Chie

**Comment by BillyMassey** [comment]
Hi Chie, omitting that tag will make it look really zoomed out and you'll have to pinch zoom to view it.  I might suggest omitting that tag on the next application, the nomster one, and comparing the experience on mobile to your splurty app then.  The difference will be very apparent.

Hope this helps!
